version: '3'

services:
  backend:
    container_name: backend
    restart: always
    build: ./backend
    ports:
      - "8000:8000"
    command: gunicorn server:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000
  
  nginx:
    container_name: nginx
    restart: always
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - backend
