scrape_configs:
  - job_name: prometheus
  scrape_interval: 10s
  static_configs:
    - targets:
        - prometheus:9090

  - job_name: cAdvisor
  scrape_interval: 10s
  static_configs:
    - targets:
        - cAdvisor:8080

  - job_name: node_exporter
  scrape_interval: 10s
  static_configs:
    - targets:
        - node_exporter:9100

  - job_name: backend
  scrape_interval: 10s
  dns_sd_configs:
    - names: ['backend']
      port: 8000
      type: A
      refresh_interval: 10s